import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/layout/Navbar/Navbar";
import { ThemeProvider } from "@/components/theme-provider"
import TopHeader from "@/components/layout/TopHeader/TopHeader";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={``}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <TopHeader />
          <Navbar />
          <div className="container">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
